API:
  Listen: localhost
  Port: 80
  Domain: domain.com
  Debug: false
Postgres:
  User: vpnuser
  Host: localhost
  DBName: vpnservice
  Password: password
  SSLMode: disable
Wireguard:
  Interface: wg0
  DNS: 10.0.0.1
  Port: 51820