API:
  Listen: 127.0.0.1
  Port: 8088
  Domain: api.nermline.xyz
Postgres:
  User: vpnuser
  Host: localhost
  DBName: vpnservice
  Password: 1423
  SSLMode: disable
Wireguard:
  Interface: wg0
  DNS: 10.0.0.1
  Port: 51820